site_name: RFviewJS
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - javascript
pages:
    - 'Overview': 'index.md'
    - 'User interfaces': 'interfaces.md'
    - 'API': 'api.md'
    - 'File formats': 'file-formats.md'
markdown_extensions:
    - markdown.extensions.admonition
